"""Check the self-contained static site before publication; no packages needed."""
from html.parser import HTMLParser
from pathlib import Path
import re
from urllib.parse import unquote, urlsplit

SITE = Path(__file__).resolve().parents[1] / 'site'
errors = []
documents = {}


class Page(HTMLParser):
    def __init__(self, path):
        super().__init__(convert_charrefs=True)
        self.path, self.ids, self.links = path, set(), []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if 'id' in attrs:
            if attrs['id'] in self.ids:
                errors.append(f'{self.path.relative_to(SITE)}: duplicate ID {attrs["id"]}')
            self.ids.add(attrs['id'])
        for key in ('href', 'src', 'poster'):
            if attrs.get(key):
                self.links.append(attrs[key])
        if attrs.get('srcset') and not attrs['srcset'].startswith('data:'):
            self.links.extend(item.strip().split()[0] for item in attrs['srcset'].split(','))


def check_url(url, source, *, anchors=True):
    parsed = urlsplit(url)
    if parsed.scheme or parsed.netloc:
        return
    raw = unquote(parsed.path)
    target = ((SITE / raw.lstrip('/')) if raw.startswith('/') else (source.parent / raw)).resolve() if raw else source
    if not target.is_relative_to(SITE.resolve()):
        errors.append(f'{source.relative_to(SITE)}: URL escapes the site: {url}')
        return
    if target.is_dir():
        target /= 'index.html'
    if not target.is_file():
        errors.append(f'{source.relative_to(SITE)}: missing resource {url}')
    elif anchors and parsed.fragment and target in documents and unquote(parsed.fragment) not in documents[target].ids:
        errors.append(f'{source.relative_to(SITE)}: missing anchor {url}')


for path in SITE.rglob('*'):
    if not path.is_file():
        continue
    if path.stat().st_size >= 100 * 1024 * 1024:
        errors.append(f'File exceeds GitHub upload limit: {path.relative_to(SITE)}')
    if path.suffix.lower() == '.html':
        doc = Page(path)
        doc.feed(path.read_text())
        documents[path.resolve()] = doc

for path, doc in documents.items():
    for url in doc.links:
        check_url(url, path)

for path in SITE.rglob('*'):
    if not path.is_file() or path.suffix not in ('.css', '.js', '.mjs', '.html', '.HTML', '.svg'):
        continue
    text = path.read_text()
    if any(marker in text for marker in ('/Users/', 'localhost:', '127.0.0.1:', 'BRAINSTORM_TOKEN', 'file://')):
        errors.append(f'{path.relative_to(SITE)}: development-only reference remains')
    for match in re.finditer(r'''url\(\s*(?:"([^"]*)"|'([^']*)'|([^)]*))\s*\)''', text):
        url = next(part for part in match.groups() if part is not None).strip()
        if not url.startswith('#'):
            check_url(url, path, anchors=False)
    if path.suffix in ('.js', '.mjs'):
        for url in re.findall(r'(?:from\s*|import\s*\(?)\s*[\"\']([^\"\']+)[\"\']', text):
            if url.startswith('.'):
                check_url(url, path)

# URLs fetched or generated by the standalone Tangible Views notes UI.
notes = SITE / 'projects/tangible-views/project-notes.html'
for name in ('validation-report.json', 'docs/ARCHITECTURE.md', 'docs/UI-CHECKS.md', 'docs/PRINCIPLES.zh-CN.md'):
    check_url(name, notes)

if errors:
    print('\n'.join(errors))
    raise SystemExit(f'Failed: {len(errors)} issue(s).')
total = sum(p.stat().st_size for p in SITE.rglob('*') if p.is_file())
print(f'PASS: {len(documents)} pages, local links, anchors, styles and module imports; {total / 1024 / 1024:.1f} MB.')
